"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const migrationPath = path.join(root, "supabase/migrations/20261002120000_acob_oem_authority.sql");
const rollbackPath = path.join(root, "supabase/rollbacks/20261002120000_acob_oem_authority.rollback.sql");
assert.equal(fs.existsSync(migrationPath), true, "authority migration missing");
assert.equal(fs.existsSync(rollbackPath), true, "authority rollback missing");
const migration = fs.readFileSync(migrationPath, "utf8").toLowerCase();
const rollback = fs.readFileSync(rollbackPath, "utf8").toLowerCase();
assert.match(migration, /lower\(au\.email\)=lower\('admin@acoblighting\.com'\)/);
assert.match(migration, /u\.role_key='super-admin'/);
assert.match(migration, /slug='acob-lighting' and status='draft'/);
assert.match(migration, /insert into public\.oem_tenant_memberships/);
assert.match(migration, /insert into public\.oem_actor_installation_access/);
assert.match(migration, /update public\.tenants set status='active'/);
assert.doesNotMatch(migration, /update public\.oem_installations set status='active'/);
assert.doesNotMatch(migration, /production_activation_authorized[^;]*true/);
assert.match(rollback, /delete from public\.oem_actor_installation_access/);
assert.match(rollback, /delete from public\.oem_tenant_memberships/);
assert.match(rollback, /update public\.tenants set status='draft'/);
console.log("ACOB OEM authority migration passed");
